kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim 
  namespace: httpd-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
